# 1. pytorch基本操作

In [1]:
import torch
torch.__version__

'1.12.1'

In [2]:
x = torch.empty(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
x = torch.rand(5,3) #tensor张量的意思

x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

view 可以改变矩阵的维度

In [4]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [5]:
a = torch.ones(5)
b = a.numpy()
b

(torch.Tensor, array([1., 1., 1., 1., 1.], dtype=float32))

In [6]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
b


tensor([1., 1., 1., 1., 1.], dtype=torch.float64)