In [1]:
import torch

#requires_grad = True表明可以对当前的x进行求导
x = torch.randn(3,4,requires_grad = True)

#等价于 x = torch.randn(3,4) x.requires_grad = True

x

tensor([[ 1.4854, -0.6951,  0.7735, -0.6029],
        [ 1.2850, -0.3184, -0.7777,  0.5343],
        [ 0.6766, -0.9403,  1.0232, -0.4793]], requires_grad=True)

In [2]:
b = torch.randn(3,4,requires_grad = True)

t = b + x

y = t.sum()
y

tensor(3.9596, grad_fn=<SumBackward0>)

In [3]:
y.backward()
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [4]:
x = torch.rand(1)
b = torch.rand(1,requires_grad = True)
w = torch.rand(1,requires_grad = True)
y = w * x
z = y + b

x.requires_grad, b.requires_grad, w.requires_grad, y.requires_grad

(False, True, True, True)

In [5]:
x.is_leaf, b.is_leaf, w.is_leaf, y.is_leaf

(True, True, True, False)

In [6]:
z. backward(retain_graph = True)

w.grad

tensor([0.0218])

In [7]:
b.grad

tensor([1.])

# 线性回归

In [8]:
import numpy as np
import torch
import torch.nn as nn

x_values = [i for i in range(11)]
x_train = np.array(x_values,dtype = np.float32)
x_train = x_train.reshape(-1,1) #把数据转换为矩阵的形式
x_train.shape

(11, 1)

In [9]:
y_values = [2 * i + 1 for i in x_values]
y_train = np.array(y_values,dtype = np.float32)
y_train = y_train.reshape(-1,1)
y_train.shape

(11, 1)


# 线性回归模型

In [10]:
class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self). __init__()
        self.linear = nn.Linear(input_dim, output_dim)
        
    def forward(self,x):
        out = self.linear(x)
        return out

input_dim = 1
output_dim = 1

model = LinearRegressionModel(input_dim,output_dim)

# 线性回归

In [11]:
epochs = 1000
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate) #指定一个优化器
criterion = nn.MSELoss()

In [12]:
for epoch in range(epochs):
    epoch += 1
    inputs = torch.from_numpy(x_train)
    labels = torch.from_numpy(y_train)
    
    #梯度每一次都需要清零
    optimizer.zero_grad()
    
    #前向传播
    outputs = model(inputs)
    
    #计算损失
    loss = criterion(outputs,labels)
    
    #反向传播
    loss.backward()
    
    #更新权重参数
    optimizer.step()
    
    #每隔五十次进行一次打印
    if epoch % 50 == 0:
        print('epoch {},loss {}'.format(epoch,loss.item()))
    

epoch 50,loss 0.3989797830581665
epoch 100,loss 0.22756318747997284
epoch 150,loss 0.12979353964328766
epoch 200,loss 0.07402929663658142
epoch 250,loss 0.042223576456308365
epoch 300,loss 0.024082763120532036
epoch 350,loss 0.013735874556005001
epoch 400,loss 0.007834459654986858
epoch 450,loss 0.0044684745371341705
epoch 500,loss 0.002548651769757271
epoch 550,loss 0.001453628297895193
epoch 600,loss 0.0008291022386401892
epoch 650,loss 0.0004728909698314965
epoch 700,loss 0.0002697214367799461
epoch 750,loss 0.00015383634308818728
epoch 800,loss 8.774390153121203e-05
epoch 850,loss 5.004580816603266e-05
epoch 900,loss 2.8545066015794873e-05
epoch 950,loss 1.6283036529785022e-05
epoch 1000,loss 9.285477062803693e-06


In [13]:
predicted = model(torch.form_numpy(x_train).requires_grad_()).data.numpy()
predicted

AttributeError: module 'torch' has no attribute 'form_numpy'

# 模型的保存和读取

In [ ]:
torch.save(model.state_dict(),'model.pkl')
model.load_state_dict(torch.load('model.pkl'))